language: node_js
node_js:
  - "10.4.1"
sudo: true

addons:
  chrome: stable

branches:
  only:
    - master

before_script:
  - npm install -g @angular/cli

script:
  - yarn all_tests #Uses yarn to run our custom script all_tests
  - yarn build --prod --base-href $base_href